version: '3.4'

services:
 mongo:
  image: mongo
  restart: always
  ports:
   - "27017:27017"

 mongo-express:
  image: mongo-express
  restart: always
  ports:
   - "5001:8081"
  depends_on:
   - mongo

 crudr:
  image: ${DOCKER_REGISTRY-}crudr
  build:
   context: .
   dockerfile: src/CrudR.Api/Dockerfile
  environment:
   - DatabaseOptions__ConnectionString=mongodb://mongo:27017
   - DatabaseOptions__DatabaseName=crudr-store
   - ApplicationOptions__EnableSwaggerUI=true
   - ApplicationOptions__RequireRevisionMatching=false
   - ApplicationOptions__BaseControllerName=
   - ApplicationOptions__UseAuthentication=false
   - ApplicationOptions__UseHealthChecks=true
   - ApplicationOptions__LivenessEndpoint=/health/live
   - ApplicationOptions__ReadinessEndpoint=/health/ready
  ports:
   - "5000:80"
  links:
   - mongo
  depends_on:
   - mongo
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:5000/health/ready"]
   interval: 2m
   timeout: 10s
   retries: 3
   start_period: 30s
